### ISSUE TITLE
Continue with refactoring of global maps

### ISSUE THREAD

**Issue by lmcmicu** [jamesaoverton/hipc-gates#18]
The class `IriMaps` in `common.py` manages some of the maps used by different modules, and contains static methods to extract others from a given data set. This mix of instance properties and static methods is not very elegant and is confusing. Either all the maps should be attached to instances of the class, or else all of them should be extractable via static methods. I lean towards the former.

**Comment by jamesaoverton** [comment]
Yes, we should be consistent. You can decide which approach is better.
