### ISSUE TITLE
Add preferred labels

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/hipc-gates#2]
Most of our gate terms come from the Protein Ontology (PR). PR uses the `rdfs:label` predicate to indicate their primary labels. These primary labels are correct and informative, but usually too long for our purposes. Instead we want to use one of the synonyms PR provides.

The synonym we want uses the `oio:hasExactSynonym` predicate annotated with a `oboInOwl:hasSynonymType` of 'http://purl.obolibrary.org/obo/pr#PRO-short-label'. It's a little tricky to extract these.

Here's a fragment of `pr.owl`. We want to extract the pair of the term ID 'http://purl.obolibrary.org/obo/PR_000000005' and the short label 'TGFBR2'.

```
    <owl:Axiom>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PRO:DNx</oboInOwl:hasDbXref>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">TGFBR2</owl:annotatedTarget>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/PR_000000005"/>
        <oboInOwl:hasSynonymType rdf:resource="http://purl.obolibrary.org/obo/pr#PRO-short-label"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasExactSynonym"/>
    </owl:Axiom>
```

There are two main options:

1. We can process the XML and look for this pattern.
2. We can use `rapper` to convert the XML to N-Triples format (line-based), then look for the pattern on consecutive lines. In N-Triples the same example looks like this:

```
_:genid132818 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Axiom> .
_:genid132818 <http://www.geneontology.org/formats/oboInOwl#hasDbXref> "PRO:DNx"^^<http://www.w3.org/2001/XMLSchema#string> .
_:genid132818 <http://www.w3.org/2002/07/owl#annotatedTarget> "TGFBR2"^^<http://www.w3.org/2001/XMLSchema#string> .
_:genid132818 <http://www.w3.org/2002/07/owl#annotatedSource> <http://purl.obolibrary.org/obo/PR_000000005> .
_:genid132818 <http://www.geneontology.org/formats/oboInOwl#hasSynonymType> <http://purl.obolibrary.org/obo/pr#PRO-short-label> .
_:genid132818 <http://www.w3.org/2002/07/owl#annotatedProperty> <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> .
```

Note that `_:genid132818` is not a stable identifier, and may change on each run.

When doing batch processing, we'll use these labels to generate a new 'Gating preferred label' column.

**Comment by lmcmicu** [comment]
Can I rely on the genids coming from rapper being sorted? It is not a show stopper if I can't but it will speed up the processing. It seems so from what I can see.

**Comment by jamesaoverton** [comment]
Sorry, I really don't know. Every tool uses a different strategy for that.
