### ISSUE TITLE
Refactor code for better sharing

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/hipc-gates#4]
The batch processing and web page are doing a lot of the same things, and should share more code.

The history is that I wrote the batch processing first, then wrote `server.py` from scratch (in a hurry). The key difference is that the batch processing scripts need to ingest legacy data, while the web site needs to validate new data.

**Comment by lmcmicu** [comment]
@jamesaoverton Assigned to you for review of PR https://github.com/jamesaoverton/hipc-gates/pull/7

**Comment by lmcmicu** [comment]
@jamesaoverton There are merge conflicts so re-assign this back to me when the review is done please so I can do the manual merge.
